### ISSUE TITLE
Using mod in 1.15 makes the screen black after you click continue on the safety screen.

### ISSUE THREAD

**Issue by Rhys-Woolcott** [Auros/Enhancements#12]
This mod currently causes a black screen in the 1.15 update

**Comment by Auros** [comment]
Please use the latest version on ModAssistant

**Comment by Rhys-Woolcott** [comment]
I am

**Comment by Auros** [comment]
Please send me your log at Beat Saber/Logs/_latest.log

**Comment by Rhys-Woolcott** [comment]
wow, very fast update in the releases. Props to you

**Comment by Auros** [comment]
It's been updated, just forgot to post it here.

**Comment by Rhys-Woolcott** [comment]
Ah, fair enough. Have a nice day
