### ISSUE TITLE
Allow clock customization

### ISSUE THREAD

**Issue by Kronzky** [Auros/Enhancements#14]
Would it be possible to allow users to customize the clock style/position (e.g. via a config file)?

I like having one in the game, but right now it's a bit too prominent — staring me in the face all the time... ;)
I'd rather have it at the side somewhere, where I could glance at it when needed.

**Comment by Auros** [comment]
This is in the Enhancements settings. The ability to move the clock as well as change its color, if it shows when playing a song, its font, its size, and more are all in the menu. (Mod Buttons -> Enhancements -> Clock icon on floor)

**Comment by Kronzky** [comment]
Oh... Very nice! And better than I had hoped for! :)
Great job!
